os:
  - linux
  - osx

python: 3.8.1
dist: bionic

# TODO: save resources by only building merge candidates and master
#branches:
#  only:
#    - master

language:
  - cpp

compiler:
  - gcc
  - clang

before_install:
  - ./ci/travis_setup.sh

script:
  - ./ci/travis_build.sh
